[package]
name = "flowrider-bmp"
version = "0.1.0"
authors = ["Cameron Daniel <cam.daniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
fern = { version = "0.5", features = ["colored"] }
structopt = "0.2"

# flowrider-metrics = { path = "../flowrider-metrics" }

serde = "1"
serde_yaml = "0.8"
serde_derive = "1"

# bgp-rs = "0.5"
bgp-rs = { path = "../bgp-rs" }
byteorder = { version = "1.3", features = ['i128'] }
chrono = "0.4"
hashbrown = "0.5"
lazy_static = "1.3"
prometheus = { version = "0.7", features = ["nightly"] }
# prometheus_exporter = "0.3"
rand = "0.6"